root: true
env:
  node: true
  es6: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2020
  project: ./tsconfig.json
  sourceType: module
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
plugins:
  - import
  - sort-keys-fix
  - typescript-sort-keys
  - unused-imports
rules:
  no-undef: off
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
        - object
        - type
      newlines-between: always
      alphabetize:
        order: asc
  import/no-duplicates: 2
  sort-keys-fix/sort-keys-fix: 2
  typescript-sort-keys/interface: 2
  unused-imports/no-unused-imports: 2
  '@typescript-eslint/no-explicit-any': 1
  '@typescript-eslint/no-unused-vars': 1
