root: true
env:
  node: true
  es6: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  project: ./tsconfig.json
  sourceType: module
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
plugins:
  - import
  - sort-keys-fix
  - typescript-sort-keys
  - unused-imports
rules:
  no-undef: off
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
        - object
        - type
      newlines-between: always
      alphabetize:
        order: asc
  import/no-duplicates: error
  sort-keys-fix/sort-keys-fix: error
  typescript-sort-keys/interface: error
  unused-imports/no-unused-imports: error
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-unused-vars': off
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/no-namespace': off
